github.com:
    users:
        ByteMe6:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: ByteMe6
